name: Tests and Coverage

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Determine test mode
        id: test_mode
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            
            # Get previous tags to determine if it's a major version bump
            PREV_TAG=$(git describe --tags --abbrev=0 ${GITHUB_REF}^ 2>/dev/null || echo "v0.0.0")
            
            if [[ "${PREV_TAG}" =~ ^v([0-9]+)\. ]]; then
              PREV_MAJOR="${BASH_REMATCH[1]}"
              if [[ "${MAJOR}" != "${PREV_MAJOR}" ]]; then
                echo "mode=full" >> $GITHUB_OUTPUT
                echo "### Major Version Release - Running Full Tests 🚀" >> $GITHUB_STEP_SUMMARY
              else
                echo "mode=fast" >> $GITHUB_OUTPUT
                echo "### Minor/Patch Version - Running Fast Tests ⚡" >> $GITHUB_STEP_SUMMARY
              fi
            else
              echo "mode=fast" >> $GITHUB_OUTPUT
            fi
          else
            echo "mode=fast" >> $GITHUB_OUTPUT
            echo "### Running Fast Tests ⚡" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Run tests (fast mode)
        if: steps.test_mode.outputs.mode == 'fast'
        run: |
          pytest tests/ -v -m "not slow" --cov=src/yetanotherspdnet --cov-report=xml --cov-report=term
      
      - name: Run tests (full mode)
        if: steps.test_mode.outputs.mode == 'full'
        run: |
          pytest tests/ -v --cov=src/yetanotherspdnet --cov-report=xml --cov-report=term
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.python-version }}
          fail_ci_if_error: false
      
      - name: Test Summary
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Python Version:** ${{ matrix.python-version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Test Mode:** ${{ steps.test_mode.outputs.mode }}" >> $GITHUB_STEP_SUMMARY
          if [ -f coverage.xml ]; then
            echo "**Coverage:** Report uploaded to Codecov ✅" >> $GITHUB_STEP_SUMMARY
          fi
